# Generated by Django 3.0.3 on 2020-02-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDatabaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.CharField(default='02/20/2020, 15:50:20', editable=False, max_length=100)),
                ('File_Type', models.CharField(choices=[('Training File', 'TrainingFile'), ('Testing File', 'TestingFile')], max_length=20, unique=True)),
                ('File_Path', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
            ],
        ),
    ]
