# Generated by Django 3.0.3 on 2020-02-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_email', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50, null=True)),
                ('booked_date', models.CharField(max_length=50)),
                ('booked_time', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('patient_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ExtendedPatientsDetail')),
            ],
        ),
    ]
